import React, { useState, useEffect } from 'react';
import { useAdminAuth } from '../useAdminAuth';
import { CreditCard, Loader2, Image, Download, ExternalLink } from 'lucide-react';

export default function SocialCards() {
  const { adminFetch } = useAdminAuth();
  const [cards, setCards] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetch_ = async () => {
      try {
        const res = await adminFetch('/api/admin/social-cards');
        if (res.ok) setCards(await res.json());
      } catch {}
      setLoading(false);
    };
    fetch_();
  }, [adminFetch]);

  return (
    <div className="space-y-6 max-w-7xl">
      <div>
        <h1 className="text-xl font-bold text-white">Social Cards</h1>
        <p className="text-xs text-slate-500 mt-1">Shareable credit score cards generated by users</p>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
        <div className="bg-[#12121E] border border-[#1E1E2A] rounded-2xl p-4">
          <p className="text-lg font-bold text-white">{cards.length}</p>
          <p className="text-[10px] text-slate-500">Total Cards Generated</p>
        </div>
        <div className="bg-[#12121E] border border-[#1E1E2A] rounded-2xl p-4">
          <p className="text-lg font-bold text-white">{cards.filter((c) => c.shared).length}</p>
          <p className="text-[10px] text-slate-500">Shared on X</p>
        </div>
        <div className="bg-[#12121E] border border-[#1E1E2A] rounded-2xl p-4">
          <p className="text-lg font-bold text-white">{cards.reduce((s, c) => s + (c.impressions || 0), 0)}</p>
          <p className="text-[10px] text-slate-500">Total Impressions</p>
        </div>
      </div>

      <div className="bg-[#12121E] border border-[#1E1E2A] rounded-2xl overflow-hidden">
        {loading ? (
          <div className="flex items-center justify-center py-20"><Loader2 className="w-6 h-6 text-[#EC81FF] animate-spin" /></div>
        ) : cards.length === 0 ? (
          <div className="flex items-center justify-center py-16">
            <div className="text-center">
              <Image className="w-8 h-8 text-slate-600 mx-auto mb-2" />
              <p className="text-xs text-slate-500">No social cards generated yet.</p>
              <p className="text-[10px] text-slate-600 mt-1">Users generate cards from the main app to share their credit score on social media.</p>
            </div>
          </div>
        ) : (
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3 p-4">
            {cards.map((c, i) => (
              <div key={c.id || i} className="bg-[#0A0A12] border border-[#1E1E2A] rounded-xl overflow-hidden group">
                <div className="aspect-video bg-gradient-to-br from-[#EC81FF]/20 to-[#0A0A12] flex items-center justify-center">
                  <CreditCard className="w-8 h-8 text-[#EC81FF]/40" />
                </div>
                <div className="p-3">
                  <p className="text-xs text-white font-mono truncate">{c.wallet?.slice(0, 6)}...{c.wallet?.slice(-4)}</p>
                  <p className="text-[10px] text-slate-500 mt-0.5">Score: {c.score} &middot; {c.shared ? 'Shared' : 'Not shared'}</p>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
